# Generated by Django 3.2 on 2021-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CLOSED', 'Закрыт')], db_index=True, default='NEW', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
