# Generated by Django 3.2 on 2022-01-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_rename_created_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='call_date',
            new_name='called_at',
        ),
    ]
