# Generated by Django 3.2 on 2022-01-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_rename_call_date_order_called_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='delivered_at',
        ),
    ]
