# Generated by Django 3.2 on 2022-03-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_rename_delivery_date_order_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UNDEFINED', 'Не известен'), ('CARD', 'Картой'), ('CASH', 'Наличными')], default='UNDEFINED', max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
